export const ADD_ITEM="ADD_ITEM";
export const REMOVE_ITEM="REMOVE_ITEM";
export const INGREDIENT_FETCHED="INGREDIENT_FETCHED";

export const BURGER_PURCHASE_SUCCESS="BURGER_PURCHASE_SUCCESS";
export const BURGER_PURCHASE_FAIL="BURGER_PURCHASE_FAIL";
export const BURGER_PURCHASE_PROCESSING="BURGER_PURCHASE_PROCESSING";

export const FETCH_ORDER_SUCCESS="FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL="FETCH_ORDER_FAIL";
export const FETCH_ORDER_PROCESSING="FETCH_ORDER_PROCESSING";

export const AUTH_PROCESSING="AUTH_PROCESSING";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";
export const LOGOUT="LOGOUT";
export const SIGN_UP_TO_AUTH="SIGN_UP_TO_AUTH";